spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/dmt
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  liquibase:
    default-schema: public


  security:
    oauth2:
      client:
        registration:
          identity:
            client-id: dmt-identity
            client-secret: 0gknA0RR7FLHakMB2vZ8DVqcnSaw5iIo
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          identity:
            token-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/token"
            authorization-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/auth"
            user-info-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/userinfo"
            jwk-set-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/certs"
            user-name-attribute: sub
vanadium:
  dmt:
    authentication:
      jwt-secret: secret
      access-token-expiration: 10d
      refresh-token-expiration: 30d