spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/dmt
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  liquibase:
    default-schema: public

  security:
    oauth2:
      client:
        registration:
          identity:
            client-id: dmt-identity
            client-secret: LfuTNZvylIfB7vvEHdQLtLnhwPVCpIWt
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          identity:
            token-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/token"
            authorization-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/auth"
            user-info-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/userinfo"
            jwk-set-uri: "http://localhost:18080/realms/dmt/protocol/openid-connect/certs"
            user-name-attribute: sub
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
  jpa:
    show-sql: true
vanadium:
  dmt:
    authentication:
      jwt-secret: secret
      access-token-expiration: 10d
      refresh-token-expiration: 30d
      post-authentication-redirect: http://localhost:3000/auth/oauth2/token/{token}
    integration:
      keycloak:
        username: dmt-master-svc
        password: admin
        server-url: http://localhost:18080
        dmt-identity-client-id: f3b4837b-58c5-42ed-92c7-297c6fbf8c13
      storage:
        s3:
          access-key: raE9ZH7SizjlDGiwUXMR
          secret-key: tokTtEBj0kfBTGbJmnwL46yQboEJOIXFZxK8EQ2j
          host: http://localhost:9000
          bucket: dmt
    file:
      upload:
        preflight-jwt-secret: secret
        preflight-file-retention: 15m
logging:
  level:
    dev.vanadium.dmt: debug
